# Week 1_Bai1

In [1]:
import numpy as np
from scipy.linalg import svd 

In [2]:
# Define a rectangular matrix 
A = np.array([[1, 0, 0, 0 ,2], 
              [0, 0, 3, 0, 0], 
              [0, 0, 0, 0, 0], 
              [0, 2, 0, 0, 0]]) 
# Compute the singular value decomposition (SVD) of A 
U, S_diag, V = svd(A) 
print(f"Left Singular Vectors (U):") 
print(U) 
print("Singular Values (S_diag):") 
print(S_diag) 
print("Right Singular Vectors (V):") 
print(V)


Left Singular Vectors (U):
[[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]]
Singular Values (S_diag):
[3.         2.23606798 2.         0.        ]
Right Singular Vectors (V):
[[-0.          0.          1.         -0.          0.        ]
 [ 0.4472136  -0.         -0.         -0.          0.89442719]
 [-0.          1.          0.         -0.          0.        ]
 [ 0.          0.          0.          1.          0.        ]
 [-0.89442719  0.          0.          0.          0.4472136 ]]


In [4]:

Sigma = np.zeros((4, 5))
for i in range(min(4, 5)):
    Sigma[i, i] = S_diag[i]
print(Sigma)

[[3.         0.         0.         0.         0.        ]
 [0.         2.23606798 0.         0.         0.        ]
 [0.         0.         2.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]]
