# Bai 2

In [52]:
import numpy as np
from scipy.linalg import svd 

In [53]:
A = np.array([[1, 0, 0, 0 ,2], 
              [0, 0, 3, 0, 0], 
              [0, 0, 0, 0, 0], 
              [0, 2, 0, 0, 0]]) 

U, S_diag, V = svd(A) 
print(f"Left Singular Vectors (U):") 
print(U) 
print("Singular Values (S_diag):") 
print(S_diag) 
print("Right Singular Vectors (V):") 
print(V)
Sigma = np.zeros((4, 5))
for i in range(min(4, 5)):
    Sigma[i, i] = S_diag[i]
print("Sigma:")
print(Sigma)



Left Singular Vectors (U):
[[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]]
Singular Values (S_diag):
[3.         2.23606798 2.         0.        ]
Right Singular Vectors (V):
[[-0.          0.          1.         -0.          0.        ]
 [ 0.4472136  -0.         -0.         -0.          0.89442719]
 [-0.          1.          0.         -0.          0.        ]
 [ 0.          0.          0.          1.          0.        ]
 [-0.89442719  0.          0.          0.          0.4472136 ]]
Sigma:
[[3.         0.         0.         0.         0.        ]
 [0.         2.23606798 0.         0.         0.        ]
 [0.         0.         2.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]]


In [54]:
# tim so gia tri lambda khác 0
r = np.count_nonzero(S_diag)
# Giữ lại r hàng và r cột đầu tiên của ma trận Sigma
Sigma_r = np.diag(S_diag[:r])
print("Sigma_r:\n", Sigma_r)
# Giữ lại r cột đầu tiên của ma trận U
U_r = U[:, :r] 
print("U_r:\n", U_r)
# Giữ lại r hàng đầu tiên của ma trận V
V_r = V[:r, :]
print("V_r:\n", V)



Sigma_r:
 [[3.         0.         0.        ]
 [0.         2.23606798 0.        ]
 [0.         0.         2.        ]]
U_r:
 [[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]]
V_r:
 [[-0.          0.          1.         -0.          0.        ]
 [ 0.4472136  -0.         -0.         -0.          0.89442719]
 [-0.          1.          0.         -0.          0.        ]
 [ 0.          0.          0.          1.          0.        ]
 [-0.89442719  0.          0.          0.          0.4472136 ]]
