In [1]:
import numpy as np
from scipy.linalg import svd 

In [7]:
A = np.array([[1.01, 0.9, 0.2, 1.001, 0.3],
             [0.2, 1.01, 0.3, 0.8, 0.4],
             [1, 1.002, 2, 0.98, 2],
             [0.3, 2, 0.4, 1.01, 0.9],
             [1.1, 0.2, 0.03, 2, 0.87]])
A.shape

U, S_diag, V = svd(A) 
print(f"Left Singular Vectors (U):") 
print(U) 
print("Singular Values (S_diag):") 
print(S_diag) 
print("Right Singular Vectors (V):") 
print(V)


Sigma = np.zeros((5, 5))
for i in range(min(5, 5)):
    Sigma[i, i] = S_diag[i]
print("Sigma:")
print(Sigma)

Left Singular Vectors (U):
[[-0.32813554  0.32928789 -0.08780746  0.88098834  0.00677837]
 [-0.27374756  0.09123211 -0.31504405 -0.16061502 -0.88976909]
 [-0.64816455 -0.65873014  0.3795124   0.04270121 -0.01021102]
 [-0.46609071  0.0207275  -0.71918456 -0.25646457  0.44646312]
 [-0.4243012   0.66999341  0.4814364  -0.36119923  0.09397571]]
Singular Values (S_diag):
[4.68190663 1.79325215 1.57960998 0.54903356 0.17859599]
Right Singular Vectors (V):
[[-0.35047463 -0.4780765  -0.35097791 -0.5344013  -0.48973477]
 [ 0.24274782 -0.05358443 -0.66685673  0.62343097 -0.32378718]
 [ 0.3428965  -0.86035897  0.23658964  0.1699711   0.2394569 ]
 [ 0.77612359  0.16080247  0.18212689 -0.3391472  -0.47284639]
 [ 0.31352063  0.04996579 -0.5856379  -0.42642477  0.61188103]]
Sigma:
[[4.68190663 0.         0.         0.         0.        ]
 [0.         1.79325215 0.         0.         0.        ]
 [0.         0.         1.57960998 0.         0.        ]
 [0.         0.         0.         0.54903356 0. 

In [22]:
# giữ lại 4 hàng 4 cột của ma trận sigma
Sigma_k = np.diag(S_diag[:4])
print("Sigma_k:\n", Sigma_k)

# Giữ lại 4 cột đầu tiên của U
U_k  = U[:, :4] 
print("U_k:\n", U_k)

# Giữ lại 4 hàng đầu tiên của V^T
V_k = V[:4, :]
print("V_k:\n ", V_k)

# Áp dụng công thức để tính phần trăm lượng thông tin 
k = 4
A_F = np.sum(S_diag**2)
j = np.arange(1, k+1)
A_All = np.sum((A - U_k @ Sigma_k @ V_k)**2)
percent = (1 - (A_All / A_F)) * 100

print("% lượng thông tin được giữ lại: ",percent)



Sigma_k:
 [[4.68190663 0.         0.         0.        ]
 [0.         1.79325215 0.         0.        ]
 [0.         0.         1.57960998 0.        ]
 [0.         0.         0.         0.54903356]]
U_k:
 [[-0.32813554  0.32928789 -0.08780746  0.88098834]
 [-0.27374756  0.09123211 -0.31504405 -0.16061502]
 [-0.64816455 -0.65873014  0.3795124   0.04270121]
 [-0.46609071  0.0207275  -0.71918456 -0.25646457]
 [-0.4243012   0.66999341  0.4814364  -0.36119923]]
V_k:
  [[-0.35047463 -0.4780765  -0.35097791 -0.5344013  -0.48973477]
 [ 0.24274782 -0.05358443 -0.66685673  0.62343097 -0.32378718]
 [ 0.3428965  -0.86035897  0.23658964  0.1699711   0.2394569 ]
 [ 0.77612359  0.16080247  0.18212689 -0.3391472  -0.47284639]]
% lượng thông tin được giữ lại:  99.88593923179663
