In [1]:
import numpy as np
from scipy.linalg import svd 

In [19]:
A = np.array([[1.01, 0.9, 0.2, 1.001, 0.3],
             [0.2, 1.01, 0.3, 0.8, 0.4],
             [1, 1.002, 2, 0.98, 2],
             [0.3, 2, 0.4, 1.01, 0.9],
             [1.1, 0.2, 0.03, 2, 0.87]])
A.shape



(5, 5)

In [28]:

def truncated_svd(A, epsilon):

    # SVD của ma trận A
    U, S_diag, V = svd(A)

    # Tìm số k cần giữ

    sigma_squared_sum = np.sum(S_diag**2) # Tổng sigma của ma trận đường chéo
    cumulative_variance = np.cumsum(S_diag**2) / sigma_squared_sum
    k = np.argmax(cumulative_variance >= epsilon)

    # Truncated SVD
    U_k = U[:, :k]
    Sigma_k = np.diag(S_diag[:k])
    V_k = V[:k, :]

    return U_k, Sigma_k, V_k, k

U_k, Sigma_k, V_k, k = truncated_svd(A, 0.9)  # Giữ lại 90% lượng thông tin

print("U_k:")
print(U_k)

print("\nSigma_k:")
print(Sigma_k)

print("\nV_k:")
print(V_k)

print("\nSố k cần giữ:", k)


U_k:
[[-0.32813554  0.32928789]
 [-0.27374756  0.09123211]
 [-0.64816455 -0.65873014]
 [-0.46609071  0.0207275 ]
 [-0.4243012   0.66999341]]

Sigma_k:
[[4.68190663 0.        ]
 [0.         1.79325215]]

V_k:
[[-0.35047463 -0.4780765  -0.35097791 -0.5344013  -0.48973477]
 [ 0.24274782 -0.05358443 -0.66685673  0.62343097 -0.32378718]]

Số k cần tìm: 2
